---

Parameters:

  SchemaHandlerPackage:
    Type: String

Resources:

  AccountResourceExecutionRoleV1:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        {
          "Version": "2012-10-17",
          "Statement": [ 
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "ec2.amazonaws.com"
                ]
              },
              "Action": ["sts:AssumeRole"]
            } 
          ]  
        }  
      Description: Role for running Account custom resources.
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AWSOrganizationsFullAccess
      RoleName: !Sub "AccountResourceExecutionV1-${AWS::Region}"

  AccountResource:
    Type: AWS::CloudFormation::ResourceVersion
    Properties: 
      ExecutionRoleArn: !GetAtt AccountResourceExecutionRoleV1.Arn
      SchemaHandlerPackage: !Ref SchemaHandlerPackage
      TypeName: REIDDHUGHES::Demo::Account
