# https://taskfile.dev

version: '3'

vars:
  NODE_ENV: |
    [ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm";
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --silent;
    [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh";

tasks:
  install:
    cmds:
      - bash -c '{{ .NODE_ENV }} nvm install v19.8.1'

  init:
    cmds:
      - aws cloudformation deploy --template-file Delivery.yml --stack-name CustomResourcesDelivery --no-fail-on-empty-changeset
  
  build:
    cmds:
      - mkdir -p .build
      - zip -j .build/account.zip account/index.js
      - zip -j .build/account-package.zip .build/account.zip account/schema.json account/.rpdk-config


  deploy:
    cmds:
      - ./deploy.sh